import { CronoData } from 'projects/mobile/src/app/modelo/cronoData';
export interface EstadPartido{
  id?: string;
  partidoId: string;
  nombreEquipo: string;
  nombreRival: string;
  goles: number;
  lanzFallados: number;
  robos: number;
  perdidas: number;
  amarillas: number;
  rojas: number;
  azules: number;
  paradas: number;
  golesRival: number;
  dosMinutos: number;
  dosMinutosRival: number;
  tm: number;
  tmRival: number;
  crono: CronoData;
};
